<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../CommunityIntranet.BuildingBlocks/CommunityIntranet.BuildingBlocks.csproj" />
    <ProjectReference Include="../CommunityIntranet.Modules.Organizations/CommunityIntranet.Modules.Organizations.csproj" />
  </ItemGroup>
</Project>
